"""empty message

Revision ID: 78fda368e8c3
Revises: 
Create Date: 2022-04-20 19:28:42.618465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fda368e8c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('savings', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'savings')
    # ### end Alembic commands ###
